name: Build

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build on tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Build client
        working-directory: ./client
        run: |
          make all

      - name: Release client
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./client/build/dance-*.tar.gz
