name: Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Release on tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main

      - name: Build client
        working-directory: ./client
        run: make all

      - name: Release client
        uses: softprops/action-gh-release@v1
        with:
          files: ./client/build/dance-*.tar.gz
